apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aegisflow
  labels:
    app: aegisflow
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    app: aegisflow
    release: {{ .Release.Name }}
